"""
Latent Space Interposer for EveryDream2trainer
===============================================

Integrates the SD-Latent-Interposer (city96/SD-Latent-Interposer) to allow
cross-latent-space teacher → student knowledge distillation.

Primary use-case:  SD1.x / SD2  **Flow Matching** teacher
                   →  SDXL       **Flow Matching** student.

Architecture  ("clean-latent factory" recipe)
---------------------------------------------

::

    ┌─────────────────────────────────────────────────────────────────────┐
    │  Teacher (SD2 FM)  ──► interposer ──►  Student (SDXL FM)           │
    │                                                                     │
    │  1. x1^SD2  ~ N(0, I)                                              │
    │         │                                                           │
    │  2. Euler ODE  (few steps, frozen teacher UNet)                    │
    │         │    x_{t-dt} = x_t + (sigma_{t-dt} - sigma_t) · v_t      │
    │         ▼                                                           │
    │     x0^SD2   (clean SD2 latent implied by teacher)                 │
    │         │                                                           │
    │  3. interposer: v1_to_xl(x0^SD2)  ──►  x0^XL                      │
    │         │                                                           │
    │  4. Standard FM training in SDXL space:                            │
    │         x1^XL ~ N(0, I)                                            │
    │         x_t^XL = (1-t)·x0^XL + t·x1^XL                           │
    │         target  v = x1^XL - x0^XL                                 │
    └─────────────────────────────────────────────────────────────────────┘

The teacher is used as a *clean-latent factory*: run its ODE from pure noise
to produce x0^SD2, then translate to SDXL space via the v1-to-xl interposer.
The student learns a velocity field from scratch in SDXL space whose
generative distribution is guided by the teacher's aesthetics.

Public API
----------

.. code-block:: python

    from core.latent_interposer import (
        LatentSpaceType,
        LatentInterposer,
        TeacherLatentBridge,
        infer_latent_space_type,
    )

    # Simple latent conversion
    interposer = LatentInterposer()
    xl_as_v1 = interposer.convert(xl_latents, src=LatentSpaceType.SDXL, dst=LatentSpaceType.SD1)

    # Teacher-student bridge (returns None when same latent space)
    bridge = TeacherLatentBridge.for_models(teacher_model, student_model)
    if bridge is not None:
        # Returns clean SDXL latents generated by the teacher ODE
        x0_xl = bridge.generate_clean_latents_in_student_space(
            latent_shape=student_latents.shape,
            teacher_model=teacher_model,
            teacher_conditioning=teacher_cond,
            num_steps=4,
        )
"""

from __future__ import annotations

import logging
import os
from typing import Optional

import torch
import torch.nn as nn
from safetensors.torch import load_file


# ---------------------------------------------------------------------------
# Neural network layers – ported from city96/SD-Latent-Interposer
# ---------------------------------------------------------------------------

class _ResBlock(nn.Module):
    """Residual block with BatchNorm and dropout."""

    def __init__(self, ch: int):
        super().__init__()
        self.join = nn.ReLU()
        self.norm = nn.BatchNorm2d(ch)
        self.long = nn.Sequential(
            nn.Conv2d(ch, ch, kernel_size=3, stride=1, padding=1),
            nn.SiLU(),
            nn.Conv2d(ch, ch, kernel_size=3, stride=1, padding=1),
            nn.SiLU(),
            nn.Conv2d(ch, ch, kernel_size=3, stride=1, padding=1),
            nn.Dropout(0.1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.norm(x)
        return self.join(self.long(x) + x)


class _ExtractBlock(nn.Module):
    """Channel-expansion block used at the head of the interposer."""

    def __init__(self, ch_in: int, ch_out: int):
        super().__init__()
        self.join = nn.ReLU()
        self.short = nn.Conv2d(ch_in, ch_out, kernel_size=3, stride=1, padding=1)
        self.long = nn.Sequential(
            nn.Conv2d(ch_in, ch_out, kernel_size=3, stride=1, padding=1),
            nn.SiLU(),
            nn.Conv2d(ch_out, ch_out, kernel_size=3, stride=1, padding=1),
            nn.SiLU(),
            nn.Conv2d(ch_out, ch_out, kernel_size=3, stride=1, padding=1),
            nn.Dropout(0.1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.join(self.long(x) + self.short(x))


class InterposerModel(nn.Module):
    """
    Lightweight CNN that maps latents from one Stable Diffusion latent space
    to another.  Architecture from city96/SD-Latent-Interposer v4.0.

    Parameters
    ----------
    ch_in:   Number of input channels  (4 for SD1/SDXL/Cascade, 16 for SD3/Flux)
    ch_out:  Number of output channels
    ch_mid:  Width of internal feature maps  (64 by default)
    scale:   Spatial upsample factor applied inside ``core`` (1.0 = no resize)
    blocks:  Number of ``_ResBlock`` layers in ``core``
    """

    def __init__(
        self,
        ch_in: int = 4,
        ch_out: int = 4,
        ch_mid: int = 64,
        scale: float = 1.0,
        blocks: int = 12,
    ):
        super().__init__()
        self.ch_in = ch_in
        self.ch_out = ch_out
        self.ch_mid = ch_mid
        self.blocks = blocks
        self.scale = scale

        self.head = _ExtractBlock(ch_in, ch_mid)
        self.core = nn.Sequential(
            nn.Upsample(scale_factor=scale, mode="nearest"),
            *[_ResBlock(ch_mid) for _ in range(blocks)],
            nn.BatchNorm2d(ch_mid),
            nn.SiLU(),
        )
        self.tail = nn.Conv2d(ch_mid, ch_out, kernel_size=3, stride=1, padding=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y = self.head(x)
        z = self.core(y)
        return self.tail(z)


# ---------------------------------------------------------------------------
# Model configuration registry  (mirrors comfy_latent_interposer.py)
# ---------------------------------------------------------------------------

#: Mapping from ``"{src}-to-{dst}"`` key → ``InterposerModel`` constructor kwargs.
INTERPOSER_CONFIGS: dict[str, dict] = {
    "v1-to-xl": {"ch_in": 4,  "ch_out": 4,  "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "v1-to-v3": {"ch_in": 4,  "ch_out": 16, "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "xl-to-v1": {"ch_in": 4,  "ch_out": 4,  "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "xl-to-v3": {"ch_in": 4,  "ch_out": 16, "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "v3-to-v1": {"ch_in": 16, "ch_out": 4,  "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "v3-to-xl": {"ch_in": 16, "ch_out": 4,  "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "fx-to-v1": {"ch_in": 16, "ch_out": 4,  "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "fx-to-xl": {"ch_in": 16, "ch_out": 4,  "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "fx-to-v3": {"ch_in": 16, "ch_out": 16, "ch_mid": 64, "scale": 1.0, "blocks": 12},
    "ca-to-v1": {"ch_in": 4,  "ch_out": 4,  "ch_mid": 64, "scale": 0.5, "blocks": 12},
    "ca-to-xl": {"ch_in": 4,  "ch_out": 4,  "ch_mid": 64, "scale": 0.5, "blocks": 12},
    "ca-to-v3": {"ch_in": 4,  "ch_out": 16, "ch_mid": 64, "scale": 0.5, "blocks": 12},
}

#: HuggingFace Hub repository ID for pretrained weights.
_HF_REPO = "city96/SD-Latent-Interposer"

#: Model file version string (matches filenames on HF Hub).
_INTERPOSER_VERSION = "4.0"


# ---------------------------------------------------------------------------
# LatentSpaceType – string constants for readability
# ---------------------------------------------------------------------------

class LatentSpaceType:
    """
    String constants identifying each supported Stable Diffusion latent space.

    Use these when calling :meth:`LatentInterposer.convert` to make call sites
    self-documenting::

        interposer.convert(latents, src=LatentSpaceType.SDXL, dst=LatentSpaceType.SD1)

    The underlying string values (``"v1"``, ``"xl"``, …) match the naming
    convention used in the city96/SD-Latent-Interposer weight files.
    """

    #: Stable Diffusion 1.x / 2.x – 4 channels, 1/8 spatial compression.
    SD1: str = "v1"
    #: SDXL – 4 channels, 1/8 spatial compression (different VAE than SD1).
    SDXL: str = "xl"
    #: Stable Diffusion 3 – 16 channels, 1/8 spatial compression.
    SD3: str = "v3"
    #: Flux.1 – 16 channels, 1/8 spatial compression.
    FLUX: str = "fx"
    #: Stable Cascade Stage A/B – 4 channels, variable spatial compression.
    CASCADE: str = "ca"


# ---------------------------------------------------------------------------
# LatentInterposer
# ---------------------------------------------------------------------------

class LatentInterposer:
    """
    Manages loading and applying SD-Latent-Interposer models.

    Models are loaded lazily on first use and then cached in-process.
    All inference runs on CPU in ``float32`` (matching the reference
    ComfyUI implementation).

    Parameters
    ----------
    model_dir:
        Optional path to a local directory containing pre-downloaded
        ``*.safetensors`` weight files.  Three layouts are accepted:

        * Flat:       ``<model_dir>/<key>_interposer-v4.0.safetensors``
        * Versioned:  ``<model_dir>/v4.0/<key>_interposer-v4.0.safetensors``
        * Submodule:  ``SD-Latent-Interposer/models/`` next to the repo root

        Falls back to HuggingFace Hub (requires ``huggingface-hub``) when
        no local file is found.

    Example::

        interposer = LatentInterposer()
        v1_latents = interposer.convert(xl_latents, "xl", "v1")
    """

    def __init__(self, model_dir: Optional[str] = None):
        self._model_dir = model_dir
        self._cache: dict[str, InterposerModel] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def convert(
        self,
        latents: torch.Tensor,
        src: str,
        dst: str,
    ) -> torch.Tensor:
        """
        Convert *latents* from the *src* latent space to the *dst* latent space.

        The returned tensor is placed on the same device and in the same dtype
        as the input.

        Parameters
        ----------
        latents:  ``[B, C, H, W]`` latent tensor.
        src:      Source latent space code, e.g. ``"xl"`` or ``LatentSpaceType.SDXL``.
        dst:      Destination latent space code, e.g. ``"v1"`` or ``LatentSpaceType.SD1``.

        Raises
        ------
        ValueError
            If no pretrained model exists for the requested conversion.
        """
        if src == dst:
            return latents

        key = f"{src}-to-{dst}"
        if key not in INTERPOSER_CONFIGS:
            raise ValueError(
                f"No interposer model exists for '{src}' → '{dst}'.  "
                f"Available conversions: {sorted(INTERPOSER_CONFIGS.keys())}"
            )

        model = self._load_model(key)
        original_device = latents.device
        original_dtype = latents.dtype

        with torch.no_grad():
            result = model(latents.cpu().float())

        return result.to(device=original_device, dtype=original_dtype)

    def is_supported(self, src: str, dst: str) -> bool:
        """Return ``True`` if a pretrained model exists for the ``src`` → ``dst`` pair."""
        return src != dst and f"{src}-to-{dst}" in INTERPOSER_CONFIGS

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_model(self, key: str) -> InterposerModel:
        if key in self._cache:
            return self._cache[key]

        path = self._resolve_model_path(key)
        cfg = INTERPOSER_CONFIGS[key]
        model = InterposerModel(**cfg)
        model.eval()
        model.load_state_dict(load_file(path))
        self._cache[key] = model
        logging.info(f"LatentInterposer: loaded '{key}' from {path}")
        return model

    def _resolve_model_path(self, key: str) -> str:
        fname = f"{key}_interposer-v{_INTERPOSER_VERSION}.safetensors"

        if self._model_dir:
            # 1. Flat layout: <model_dir>/<fname>
            candidate = os.path.join(self._model_dir, fname)
            if os.path.isfile(candidate):
                return candidate

            # 2. Versioned layout: <model_dir>/v4.0/<fname>
            candidate = os.path.join(self._model_dir, f"v{_INTERPOSER_VERSION}", fname)
            if os.path.isfile(candidate):
                return candidate

        # 3. Bundled submodule: SD-Latent-Interposer/models/ alongside the repo root
        repo_root = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
        submodule_candidate = os.path.join(repo_root, "SD-Latent-Interposer", "models", fname)
        if os.path.isfile(submodule_candidate):
            return submodule_candidate

        versioned_submodule_candidate = os.path.join(
            repo_root, "SD-Latent-Interposer", "models", f"v{_INTERPOSER_VERSION}", fname
        )
        if os.path.isfile(versioned_submodule_candidate):
            return versioned_submodule_candidate

        # 4. HuggingFace Hub fallback
        try:
            from huggingface_hub import hf_hub_download
        except ImportError as exc:
            raise ImportError(
                "huggingface-hub is required to download interposer weights automatically.  "
                "Install with:  pip install huggingface-hub\n"
                "Or download the weights manually from "
                f"https://huggingface.co/{_HF_REPO}/tree/main/v{_INTERPOSER_VERSION}"
            ) from exc

        logging.info(f"LatentInterposer: downloading '{key}' from HuggingFace Hub …")
        return str(
            hf_hub_download(
                repo_id=_HF_REPO,
                subfolder=f"v{_INTERPOSER_VERSION}",
                filename=fname,
            )
        )


# ---------------------------------------------------------------------------
# Helper: infer latent space type from a TrainingModel
# ---------------------------------------------------------------------------

def infer_latent_space_type(model) -> Optional[str]:
    """
    Infer the latent space type for *model* and return its code string.

    Returns
    -------
    ``"xl"`` for SDXL models (``text_encoder_2`` present).
    ``"v1"`` for SD1.x / SD2.x models (4-channel UNet, no second text encoder).
    ``"v3"`` if the UNet has 16 input channels (SD3/Flux territory – callers
    should verify further before relying on this).
    ``None`` if the type cannot be reliably determined.
    """
    if model is None:
        return None

    # SDXL is identified by the presence of a second text encoder
    if getattr(model, "is_sdxl", False):
        return LatentSpaceType.SDXL

    unet = getattr(model, "unet", None)
    if unet is not None:
        in_ch = unet.config.get("in_channels", 4)
        if in_ch == 16:
            return LatentSpaceType.SD3  # SD3 / Flux – caller should verify

    return LatentSpaceType.SD1


# ---------------------------------------------------------------------------
# TeacherLatentBridge
# ---------------------------------------------------------------------------

class TeacherLatentBridge:
    """
    Bridges the latent space gap between an SD1.x / SD2 **Flow Matching**
    teacher and an **SDXL Flow Matching** student during knowledge distillation.

    The teacher is used as a **clean-latent factory**:

    1. Sample fresh Gaussian noise ``x1^SD2 ~ N(0, I)`` in teacher latent space.
    2. Run the teacher's FM ODE for ``num_steps`` Euler steps from ``σ=1`` to
       ``σ=0``, yielding a clean teacher latent ``x0^SD2``.
    3. Convert ``x0^SD2 → x0^XL`` via the ``v1-to-xl`` interposer.

    The caller then trains the student with the standard FM objective:

    .. code-block:: python

        x1^XL ~ N(0, I)
        x_t^XL = (1-t) · x0^XL  +  t · x1^XL
        target  v = x1^XL - x0^XL

    The teacher's aesthetics transfer because ``x0^XL`` inherits the teacher's
    generative distribution via the interposer.  The student learns the velocity
    field from scratch in SDXL space, where it actually lives.

    Usage
    -----
    .. code-block:: python

        bridge = TeacherLatentBridge.for_models(teacher_model, student_model)
        if bridge is not None:
            x0_xl = bridge.generate_clean_latents_in_student_space(
                latent_shape=student_latents.shape,
                teacher_model=teacher_model,
                teacher_conditioning=teacher_cond,
                num_steps=4,
            )
    """

    def __init__(
        self,
        src_space: str,   # Student's latent space, e.g. "xl"
        dst_space: str,   # Teacher's latent space, e.g. "v1"
        interposer: Optional[LatentInterposer] = None,
    ):
        self.src_space = src_space
        self.dst_space = dst_space
        self.interposer = interposer or LatentInterposer()

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def for_models(
        cls,
        teacher_model,
        student_model,
        model_dir: Optional[str] = None,
    ) -> Optional["TeacherLatentBridge"]:
        """
        Construct a bridge when *teacher_model* and *student_model* occupy
        **different** latent spaces and both use flow-matching schedules.

        Returns ``None`` when:

        * Either model is ``None``.
        * Either model is not using a flow-matching noise scheduler.
        * Both models share the same latent space (no bridge needed).
        * No pretrained interposer model exists for the detected conversion.

        Parameters
        ----------
        teacher_model:  Frozen :class:`~model.training_model.TrainingModel`.
        student_model:  Training :class:`~model.training_model.TrainingModel`.
        model_dir:      Optional path to local interposer weight files.
        """
        if teacher_model is None or student_model is None:
            return None

        teacher_is_fm = getattr(teacher_model, "is_flow_matching", False)
        student_is_fm = getattr(student_model, "is_flow_matching", False)
        if not (teacher_is_fm and student_is_fm):
            logging.debug(
                "TeacherLatentBridge.for_models: skipping – "
                "requires both teacher and student to use flow matching "
                f"(teacher={teacher_is_fm}, student={student_is_fm})"
            )
            return None

        teacher_space = infer_latent_space_type(teacher_model)
        student_space = infer_latent_space_type(student_model)

        if teacher_space is None or student_space is None:
            logging.warning(
                "TeacherLatentBridge.for_models: could not infer latent space "
                f"for teacher ({teacher_space}) or student ({student_space}). "
                "Skipping bridge."
            )
            return None

        if teacher_space == student_space:
            logging.debug(
                f"TeacherLatentBridge.for_models: teacher and student share "
                f"'{student_space}' latent space – no bridge needed."
            )
            return None

        interposer = LatentInterposer(model_dir=model_dir)

        # Both conversion directions must exist before committing
        if not interposer.is_supported(student_space, teacher_space):
            logging.warning(
                f"TeacherLatentBridge: no interposer model for "
                f"'{student_space}' → '{teacher_space}'.  "
                "Teacher guidance will not use cross-space bridging."
            )
            return None
        if not interposer.is_supported(teacher_space, student_space):
            logging.warning(
                f"TeacherLatentBridge: no interposer model for "
                f"'{teacher_space}' → '{student_space}'.  "
                "Teacher guidance will not use cross-space bridging."
            )
            return None

        bridge = cls(src_space=student_space, dst_space=teacher_space, interposer=interposer)
        logging.info(
            f"TeacherLatentBridge: active — "
            f"student '{student_space}' ↔ teacher '{teacher_space}'"
        )
        return bridge

    # ------------------------------------------------------------------
    # Convenience properties
    # ------------------------------------------------------------------

    @property
    def student_space(self) -> str:
        """Alias for ``src_space``."""
        return self.src_space

    @property
    def teacher_space(self) -> str:
        """Alias for ``dst_space``."""
        return self.dst_space

    # ------------------------------------------------------------------
    # Main computation
    # ------------------------------------------------------------------

    def generate_clean_latents_in_student_space(
        self,
        latent_shape: tuple,
        teacher_model,
        teacher_conditioning,
        num_steps: int = 4,
    ) -> torch.Tensor:
        """
        Run the frozen teacher FM ODE from pure noise to obtain clean teacher
        latents, then convert them to the student (SDXL) latent space.

        This is the "clean-latent factory" recipe:

        1. ``x1^teacher ~ N(0, I)`` – fresh noise in teacher latent space.
        2. Euler ODE from σ=1 → σ=0 with the frozen teacher UNet.
        3. ``interposer(x0^teacher)`` → ``x0^student``.

        Parameters
        ----------
        latent_shape:
            ``(B, C, H, W)`` shape of the *student* latents.  The spatial
            dimensions ``H`` and ``W`` are reused for the teacher noise; the
            channel count is taken from the teacher's UNet
            (``unet.config.in_channels``).
        teacher_model:
            Frozen :class:`~model.training_model.TrainingModel` teacher.
        teacher_conditioning:
            :class:`~model.training_model.Conditioning` for the teacher UNet
            (must have batch size matching ``latent_shape[0]``).
        num_steps:
            Number of Euler integration steps (default 4 – cheap for
            rectified-flow models).

        Returns
        -------
        torch.Tensor
            ``[B, C_student, H, W]`` clean latents in student latent space,
            on the same device and dtype as the teacher UNet.
        """
        device = teacher_model.device
        dtype = teacher_model.unet.dtype
        B = latent_shape[0]

        # Teacher-space channel count (4 for SD1/SD2/SDXL, 16 for SD3/Flux)
        teacher_ch = teacher_model.unet.config.get("in_channels", 4)
        teacher_latent_shape = (B, teacher_ch, latent_shape[2], latent_shape[3])

        # ── 1.  Sample x1^teacher ~ N(0, I) ─────────────────────────────────
        x = torch.randn(teacher_latent_shape, device=device, dtype=dtype)

        # ── 2.  Euler ODE: σ = 1 → 0  (num_steps equal steps) ───────────────
        #   Rectified flow forward:  x_t = (1−σ)·x0 + σ·x1
        #   Velocity field:          v = x1 − x0  (so dx/dσ = v)
        #   Euler reverse:           x_{σ−Δσ} = x_σ + (σ_{next} − σ_{curr})·v
        #   Since σ_{next} < σ_{curr}, the step is negative → moves toward x0.
        sigmas = torch.linspace(1.0, 0.0, num_steps + 1)  # shape [num_steps+1]

        with torch.no_grad():
            for i in range(num_steps):
                sigma_curr = sigmas[i].item()
                sigma_next = sigmas[i + 1].item()

                # Look up the shifted UNet timestep for sigma_curr
                if hasattr(teacher_model.noise_scheduler, "get_best_timestep_for_sigma"):
                    unet_t = teacher_model.noise_scheduler.get_best_timestep_for_sigma(
                        sigma_curr
                    )  # scalar tensor
                else:
                    # Fallback: linear mapping  σ → [0, 1000]
                    unet_t = torch.tensor(sigma_curr * 1000.0)

                unet_t_batch = unet_t.to(device=device, dtype=dtype).unsqueeze(0).expand(B)

                # Teacher UNet predicts velocity v = x1 − x0
                v = teacher_model.unet(
                    x,
                    unet_t_batch,
                    encoder_hidden_states=teacher_conditioning.prompt_embeds.to(
                        device=device, dtype=dtype
                    ),
                    added_cond_kwargs=(
                        teacher_conditioning.get_added_cond_kwargs(dtype=dtype)
                        if teacher_model.is_sdxl
                        else None
                    ),
                ).sample.to(torch.float32)

                # Euler step (sigma_next − sigma_curr < 0, so x moves toward x0)
                x = x.float() + (sigma_next - sigma_curr) * v
                x = x.to(dtype=dtype)

        # x is now x0^teacher (approximately)

        # ── 3.  Convert x0^teacher → x0^student via interposer ──────────────
        return self.interposer.convert(
            x.float(), src=self.dst_space, dst=self.src_space
        ).to(device=device, dtype=dtype)


